ansible_user: kevin
build_base_path: "/home/{{ ansible_user }}"
git_dir: "{{ build_base_path }}/{{ application }}"
application: apt-mirror
mirror_base_path: "/var/spool/apt-mirror"
mirror_ubuntu_version: "noble"
mirror_server_name: "archive.ubuntu.com"
